sudo: required

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo service docker restart

script:
  - cd bootstrap && make build
  - cd ..
  - cd loadtest && make build
  - cd ..

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    cd bootstrap && make push;
    cd ..;
    cd loadtest && make push;
    fi
